name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Display Directory Structure
      run: ls -R /home/ubuntu/frontend/_work/laghata-frontend/laghata-frontend/frontend

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set Working Directory and Install Dependencies
      run: |
        cd /home/ubuntu/frontend/_work/laghata-frontend/laghata-frontend/frontend
        npm install

    - name: Build
      run: npm run build --if-present
