name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Display Directory Structure
      run: ls -R
    
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build




