name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Display GitHub Workspace
      run: echo "GitHub Workspace:$GITHUB_WORKSPACE"

    - name: Display GitHub Home
      run: echo "GitHub Home:$GITHUB_HOME"

    - name: Display Directory Structure (GitHub Workspace)
      run: ls -R $GITHUB_WORKSPACE

    - name: Display Directory Structure (GitHub Home)
      run: ls -R $GITHUB_HOME

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set Working Directory
      run: cd $GITHUB_WORKSPACE/home/ubuntu/frontend/_work/laghata-frontend/laghata-frontend/frontend

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
