name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Working Directory
      run: echo "/home/ubuntu/frontend/_work/laghata-frontend/laghata-frontend/frontend" > $GITHUB_WORKSPACE/.workdir

    - name: Display Directory Structure
      run: ls -R
      working-directory: $GITHUB_WORKSPACE/.workdir

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      working-directory: $GITHUB_WORKSPACE/.workdir

    - name: Install Dependencies
      run: npm install
      working-directory: $GITHUB_WORKSPACE/.workdir

    - name: Build
      run: npm run build --if-present
      working-directory: $GITHUB_WORKSPACE/.workdir
