name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Working Directory
      run: cd /home/ubuntu/frontend/_work/laghata-frontend/laghata-frontend/frontend

    - name: Display Directory Structure
      run: ls -R
      


    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
